apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trigger-func
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/beserkobob/trigger-func
          env:
            - name: TARGET
              value: "trigger-func"
